version: "2.0"
services:
  web-1:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  web-2:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  web-3:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  web-4:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  web-5:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
  web-6:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true
    env:
      - OLLAMA_DEBUG=1
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
profiles:
  compute:
    web-1:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
    web-2:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
    web-3:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
    web-4:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
    web-5:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
    web-6:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx8000
                - model: p100
                - model: a6000
                - model: v100
                - model: rtx3090
                - model: t4
                - model: p40
  placement:
    global1:
      pricing:
        web-1:
          denom: uakt
          amount: 10000
    global2:
      pricing:
        web-2:
          denom: uakt
          amount: 10000
    global3:
      pricing:
        web-3:
          denom: uakt
          amount: 10000
    global4:
      pricing:
        web-4:
          denom: uakt
          amount: 10000
    global5:
      pricing:
        web-5:
          denom: uakt
          amount: 10000
    global6:
      pricing:
        web-6:
          denom: uakt
          amount: 10000
deployment:
  web-1:
    global1:
      profile: web-1
      count: 1
  web-2:
    global2:
      profile: web-2
      count: 1
  web-3:
    global3:
      profile: web-3
      count: 1
  web-4:
    global4:
      profile: web-4
      count: 1
  web-5:
    global5:
      profile: web-5
      count: 1
  web-6:
    global6:
      profile: web-6
      count: 1
