---
version: "2.0"
services:
  morpheus:
    image: linuxserver/webtop:amd64-ubuntu-xfce
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 11434
        as: 11434
        to:
          - global: true          
    env:
      - OLLAMA_DEBUG=1
profiles:
  compute:
    morpheus:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 64Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    dcloud:
      pricing:
        morpheus:
          denom: uakt
          amount: 1000
deployment:
  morpheus:
    dcloud:
      profile: morpheus
      count: 1

