version: "2.0"
profiles:
  compute:
    grafana:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 64GB
  placement:
    akash:
      pricing:
        grafana:
          denom: uakt
          amount: 10000
      attributes:
        host: akash
services:
  grafana:
    image: grafana/grafana
    expose:
      - as: 80
        to:
          - global: true
        port: 3000
deployment:
  grafana:
    akash:
      count: 1
      profile: grafana
